services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: auth_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: childhoodsend23
    ports:
      - "54320:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    build: .
    environment:
      POSTGRES_CONN_STR: "postgres://admin:childhoodsend23@database/auth_service?sslmode=disable"
    depends_on:
      - database
    ports:
      - "8080:8080"
